server:
  session:
    timeout: 1800
  port: 80

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml

