spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: port
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml

